### ISSUE TITLE
Is CellOracle only suitable for analysing longitudinal datasets?

### ISSUE THREAD

**Issue by JiaGuangshuai** [morris-lab/CellOracle#103]
Hi,

Is it only suitable for analysing datasets sampled at different time points or developmental dataset that contains cells at different development stages?

Can CellOracle be used to analyse 'static' scRNA-seq dataset, such as data from only one time point, like tumour-profiling scRNA-seq dataset?

For example, I would like to assess whether a certain transcription factor is important in a certain tumour, and could I verify this by in silicon perturbing this TF and inferring whether it has an effect on the whole dataset? If I use CellOracle in this scenario, does the result make sense?

Thank you!

Best regards,
Guangshuai

**Comment by KenjiKamimoto-wustl122** [comment]
@JiaGuangshuai 

Thank you for the question!
I'm Kenji, a developer of CellOracle.
That is a really important question, and happy to clarify that! 

- In principle, CellOracle is developed to analyze dynamic data such as developmental processes and cellular reprogramming. In our study (https://www.nature.com/articles/s41586-022-05688-9), we analyzed zebrafish embryogenesis (Figure 3 and 5), which include multiple time points data. And it is nice if we could use data that include multiple time points. 
- But, using single time point data is still no problem if the data includes enough heterogeneity. We analyzed mouse hematopoiesis data, which consists of single time point data (Figure1 and 2 in our paper above). In general, scRNA-seq data includes a heterogeneous population in most cases of development and tumor, and we can try to analyze that data with CellOracle.
- As another critical point of the CellOracle analysis, we need to ensure the data represents a continuous process.  Let me describe two examples. 
  1. Let's assume that you merge two healthy cell samples and tumor cell samples from really different two-time points and the data lacks intermediate states. In that case, the dimensional reduction result will show a discrete structure; we cannot make a trajectory for the conversion. Thus, CellOracle cannot analyze the transition due to the lack of transition state data.
  2.  Another bad case scenario is your data is too homogeneous. For example, if your data include only one pure population, such as a sorted cell population or pure cell line, there may be no dynamics or transitions, and CellOracle cannot analyze it. 

In your case, I assume you make scRNA-seq data in tumor tissue. I think CellOracle analysis results make sense if the data include heterogeneous cell states, such as tumor cell type, and non-tumor cell type, and intermediate cell type between them. As a practical viewpoint, please check the cell trajectory structure. If you can make continuous dimensional reduction embedding that nicely represents the biological transition events of your interest, CellOracle works well. 

Your question here is critical. Thank you for the question. I will also add this explanation to the CellOracle documentation for other users.

Best,
Kenji

**Comment by JiaGuangshuai** [comment]
Hi Kenji,

Thank you for your reply and thorough clarification.

Let me ask another example, if it is scRNA-seq profiling of a mature organ, such as adult brain or heart, it may not be suitable because the major cells are post-mitotic and in the mature state, and lack intermediate/transitory states. Even though such organs are heterogeneous containing multiple cell subpopulations, the subpopulations per se are homogeneous within themselves. 

Is my understanding correct?

Best,
Guangshuai

**Comment by KenjiKamimoto-wustl122** [comment]
@JiaGuangshuai 

Yes, I think you are correct. As you said, CellOracle may not work with a mature organ, such as brain or heart, which do not include intermediate state. If you want to analyze development of them, I would recommend taking scRNA-seq data during earlier stages.

Yes, I think you are right. As you say, CellOracle may not be applicable for mature organs that do not contain intermediate states, such as the brain and heart. If you want to analyze their development, I recommend taking scRNA-seq data from earlier stages.

However, there are also some exceptions to this. Some mature organs are still suited for CellOracle analysis; If the tissue contains tissue stem cells and continues to undergo cellular differentiation in the adult, such as the small intestine or the regenerative state, there should be a stem cell state or intermediate state, which would be worth applying CellOracle.

Best,
Kenji
