### ISSUE TITLE
Problems with reference genome for construction of base GRN from scATAC data

### ISSUE THREAD

**Issue by rickycolman** [morris-lab/CellOracle#125]
Hi, firstly thank you for this great GRN inference method and the extensive documentation that comes with it!

I'm currently running into issues constructing a baseGRN from scATAC data. I'm on the third step of the tutorial 
 working with the '02_atac_peaks_to_TFinfo_with_celloracle_20200801' notebook.   

Specifically, I have troubles with where CellOracle looks for my reference genome (hg38). I suspect, from the default download location of the `genomepy.install_genome()`, it checks `~/.local/share/genomes`. Am I correct? However, due to me working on a remote server with very limited storage space in my home directory, I was wondering if there was a parameter I could change throughout the script to set the directory for my reference genome?

I have looked into this myself in detail but have not found a way to supply f.e. `celloracle.motif_analysis.TFinfo()` with a custom reference genome location, as it seems to only take a string as input detailing the name of the reference genome, looking for this in a default location.

How could I resolve this issue?
Thank you in advance!

**Comment by DongzeHE** [comment]
Any update for this? I am also working on a remote server with weird firewall settings, which made genomepy return ` | WARNING | UCSC appears to be offline.` all the time.

**Comment by KenjiKamimoto-wustl122** [comment]
@rickycolman , @DongzeHE 

Thank you for the feedback, and sorry for the slow response.
I have updated celloracle  and our tutorials. https://morris-lab.github.io/CellOracle.documentation/notebooks/02_motif_scan/02_atac_peaks_to_TFinfo_with_celloracle_20200801.html#3.-Instantiate-TFinfo-object-and-search-for-TF-binding-motifs

Please install celloracle version 0.13.1. 

Now, we can specify custom location for the reference genome data.

For example, let's say you have installed reference genome data under `CUSTOM_DIR`. Please enter the directory information in several steps. For example, please enter the genome directory information when you create TFinfo object.

`tfi = ma.TFinfo(peak_data_frame=peaks,
                ref_genome=ref_genome,
                genomes_dir=CUSTOM_DIR)`

I hope it helps.

@DongzeHE 
1. If your environment doesn't have internet access, please place reference genome data manually and specify the location.

2. FYI you may also have another error if you want to use CellOracle default dataset because some data loading function needs internet access to download data. In that case, please do `git clone` the repository, and install celloracle from source with `pip install -e .` . It will install celloracle including all default dataset, and you don't need to use internet access.

**Comment by chenc327** [comment]
> tfi = ma.TFinfo(peak_data_frame=peaks, ref_genome=ref_genome, genomes_dir=CUSTOM_DIR)
> 
> This works but the tfi.scan() function does not take a custom dir and it will go find the genomes in the default dir.

the same question. have you solved it?

**Comment by KenjiKamimoto-wustl122** [comment]
I could not reproduce the issue.

Can you please check your reference genome is installed correctly at your custom directory?
Please see the instruction in the tutorial how to check installation status.
Please specify the directory using `genomes_dir` in the function. 
https://morris-lab.github.io/CellOracle.documentation/notebooks/02_motif_scan/02_atac_peaks_to_TFinfo_with_celloracle_20200801.html#1.-Rerefence-genome-data-preparation

If the reference genome is not installed in your custom directory, please install the reference genome as follows.

```
import genomepy
genomepy.install_genome(name=ref_genome, provider="UCSC", genomes_dir=GENOMES_DIR)
```
    
Also, please read descriptions of our tutorial for more information.https://morris-lab.github.io/CellOracle.documentation/notebooks/02_motif_scan/02_atac_peaks_to_TFinfo_with_celloracle_20200801.html#1.-Rerefence-genome-data-preparation

If you still have error, please copy and paste the whole error messages. It will help us to identify the cause of issue.

**Comment by polinaderev** [comment]
Hi! @KenjiKamimoto-ac I seem to be having the same issue as the topic starter.

I also work on a remote high performance computing cluster, it's Rocky8-based. I work in a mamba environment with CellOracle (**v0.20.0**). I do
```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os, sys, shutil, importlib, glob
from tqdm.notebook import tqdm
import celloracle as co
from celloracle import motif_analysis as ma
from celloracle.utility import save_as_pickled_object

gen_dir = "references"
ref_genome = "hg38"

wd = "repos/runx1eto-kd-aml/GRN"
in_path = "in"
```

Then, I can run
```
peaks = pd.read_csv(
    os.path.join(wd, in_path, "processed_peak_file.csv"), 
    index_col = 0)

peaks = ma.check_peak_format(peaks, 
                             ref_genome, 
                             genomes_dir = gen_dir) 

tfi = ma.TFinfo(peak_data_frame = peaks,
                ref_genome = ref_genome,
                genomes_dir = gen_dir)
```
without problems.

`tfi` gives me `<celloracle.motif_analysis.tfinfo_core.TFinfo object at 0x7f73da93b850>`.

`ma.is_genome_installed(ref_genome=ref_genome, genomes_dir=gen_dir)` gives me `True`. 

Still,
```
tfi.scan(fpr = 0.02,
         motifs = None,  
         verbose = True)
```
gives me
```
No motif data entered. Loading default motifs for your species ...
 Default motif for vertebrate: gimme.vertebrate.v5.0.
 For more information, please see https://gimmemotifs.readthedocs.io/en/master/overview.html

Initiating scanner...

2025-06-20 15:54:04,443 - DEBUG - using background: genome hg38 with size 200
Traceback (most recent call last):
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/celloracle/motif_analysis/tfinfo_core.py", line 400, in scan
    s.set_background(genome=self.ref_genome, size=background_length) # For gimmemotifs ver 14.4
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/gimmemotifs/scanner.py", line 964, in set_background
    fa = RandomGenomicFasta(genome, size, nseq)
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/gimmemotifs/background.py", line 643, in __init__
    create_random_genomic_bedfile(tmpbed, genome, size, n)
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/gimmemotifs/background.py", line 143, in create_random_genomic_bedfile
    features = Genome(genome).get_random_sequences(n, size)
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/genomepy/genome/__init__.py", line 54, in __init__
    self.filename = self._parse_filename(name)
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/genomepy/genome/__init__.py", line 139, in _parse_filename
    raise FileNotFoundError(
FileNotFoundError: could not find hg38.fa(.gz) in genome_dir /home/pmc_research/pderevianko/.local/share/genomes/hg38

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc/local/Rocky8/pmc_heidenreich/pderevianko/mambaforge/envs/celloracle_env/lib/python3.10/site-packages/celloracle/motif_analysis/tfinfo_core.py", line 402, in scan
    s.set_background(genome=self.ref_genome, length=background_length)# For old gimmemotifs ver 13
TypeError: Scanner.set_background() got an unexpected keyword argument 'length'
```

So it is indeed trying to look for the reference genome in the default home directory instead of the directory where I have installed it ("references").

How can I tell the scan function that it won't find the reference genome in my home directory?

UPD. After some reading of the code and talking about it to ChatGPT, I've been able to resolve this by
```
from norns import config as cfg
config = cfg("genomepy", default="config/default.yaml")
config.update({"genomes_dir": "/hpc/pmc_heidenreich/pderevianko/references"})
```
I do think this is worth a fix!
