### ISSUE TITLE
Error with oracle.import_anndata_as_raw_count

### ISSUE THREAD

**Issue by Hanxi-002** [morris-lab/CellOracle#172]
Hi, 
I encounter the following error when running the function 

adata.X = adata.layers["raw"].copy()
oracle.import_anndata_as_raw_count(adata=adata,
                                   cluster_column_name="louvain",
                                   embedding_name="X_tsne")

------------------------------------------------------------------------
IndexError: index 999 is out of bounds for axis 0 with size 224

The traceback points to 
self.score_cv_vs_mean(n, plot=False, max_expr_avg=35)
and 
nth_score = np.sort(score)[::-1][N]
------------------------------------------------------------------------
I've checked the dimensions of louvain and umap coordinates and they are correct. I'm not sure where the 224 is coming from.

Any help is appreciated, 
Thank you!

**Comment by KenjiKamimoto-wustl122** [comment]
The error means the number of genes in your dataset is only 224 after some quality checks and filtering. The number is at least 999.
If you used a data processing method different from what we recommend in our tutorial, this may be the reason.
Can you use our recommended preprocessing below?
https://morris-lab.github.io/CellOracle.documentation/tutorials/scrnaprocess.html

**Comment by narein97** [comment]
Hi,

I faced the same issue and it seems that there is a fixed max_expr_avg=35 when the score_cv_vs_mean function is used to filter out genes with high mean expression.  Could I know why is this value 35? Since there can exist datasets where the range of gene expression values could either be smaller or larger. In that case is there a way to modify this max_expr_avg? I followed the preprocessing steps provided in the tutorial but it does not help solve this issue.
