### ISSUE TITLE
Memory requirements for markov transitions

### ISSUE THREAD

**Issue by concatenize** [morris-lab/CellOracle#19]
Hi again! I'm running CO on a 54k-cell dataset using ~1k variable genes. The network inference and KO simulation runs fine, but I have problems with the Markov transitions used to visualize the simulated KO. My kernel keeps dying when I run `oracle.estimate_transition_prob`. I am currently running it like this:

```
oracle.estimate_transition_prob(n_neighbors=200, knn_random=True, sampled_fraction=0.01) 
```

I have had problems running velocyto.R on this same dataset in the past, and I think those were caused by storing a dense 54k by 54k matrix in memory, but I don't know if this is the same issue or not. What would you suggest doing? 

Thanks!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi, concatenize,

As you expected, I guess the problem is caused by the lack of memory. 
CellOracle's function for the transition probability calculation is based on the similar algorithm as velocyto. This function requires large amount of memory if your scRNA-seq data contains large number of cells.

I guess 54k cells are beyond the capacity of laptop. 
I guess Celloracle and Velocyto requires more than 128G memory if you use 54K cells.

There are two options. 
(1) Please downsample cells in advance of celloracle analysis. I recommend using ~10k cells or less.
(2) If you want to use 54k cells, you need more memory. It is the problem of computational resource rather than the problem of algorithm. Please use computational cloud, such as AWS or Google cloud computing.

Also, please let me add one more comment.
In the function of "oracle.estimate_transition_prob", you are setting  sampled_fraction to 0.01.
But I think 0.01 is too small. Please set this parameter more than 0.1. 
I will add more descriptions about this function in the future.

**Comment by concatenize** [comment]
OK, that makes sense. I appreciate your help.

> In the function of "oracle.estimate_transition_prob", you are setting sampled_fraction to 0.01.
> But I think 0.01 is too small. Please set this parameter more than 0.1.

I agree. This was meant to make the computation easier at first, just to get it to run, not as a final analysis. I will pursue some other option such as a larger computer, downsampling, or alternative visualization methods.
