### ISSUE TITLE
Warning messages and missing scores

### ISSUE THREAD

**Issue by gatoravi** [morris-lab/CellOracle#2]
Thank you for developing CellOracle. I'm trying out the program for the first time. I've been doing this by using the tutorial online [here.](https://morris-lab.github.io/CellOracle.documentation/)

I see a lot of warnings when I run the code related to network analysis. I think these come from the get_links() function:

I see thousands of lines that read
"modularity is implemented for undirected"

and then, I also see several instances of:
"
Warning messages:
1: In closeness(g) :
  At centrality.c:2617 :closeness centrality is not well-defined for disconnected graphs
2: In edge.betweenness.community(g) :
  At community.c:460 :Membership vector will be selected based on the lowest modularity score.
3: In edge.betweenness.community(g) :
  At community.c:467 :Modularity calculation with weighted edge betweenness community detection might not make sense -- modularity treats edge weights as similarities while edge betwenness treats them as distances
4: In leading.eigenvector.community(g, options = list(maxiter = 1e+06,  :
  At community.c:1597 :This method was developed for undirected graphs
finished
“

Does this indicate that something went wrong at this step?

When I proceed with the next steps and look at the figures in the networ_score_per_gene folder they look strange. There are missing values for most of the clusters, I've attached a plot as an example.
![score_dynamics_in_seurat_clusters_2000_Gli2](https://user-images.githubusercontent.com/764948/77384444-64424800-6d53-11ea-93f5-e168a4285df8.png)

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Avi, thank you for using CellOracle! 

First, the warning messages you got are not related to your problem in the figures. And nothing is going wrong.
CellOracle internally uses several R packages to calculate various network scores.
The current version (0.3.1) of CellOracle automatically calculates many scores, but we do not use all of them. You got the warning message when you calculate some network community, which is not used in the network analysis. Please just ignore the warnings. This will be fixed in the future version.

Missing values in your figure may be due to the network structure. CellOracle detects cluster-specific gene-gene connections, and sometimes a gene does not have any connection in a cluster. If a gene has no connections in a cluster, it is impossible to calculate network degree scores. Thus the scores will not be shown. In your figure, I guess your gene of interest has significant connections only in cluster-4 and cluster-6.
I updated our tutorials now to support this issue. Please look at the tutorials for more information.
https://morris-lab.github.io/CellOracle.documentation/notebooks/04_Network_analysis/Network_analysis_with_with_Paul_etal_2015_data.html#6.3.-Network-score-dynamics

Kenji

**Comment by gatoravi** [comment]
Thank you, this is helpful..
