### ISSUE TITLE
Degree distribution

### ISSUE THREAD

**Issue by yong114** [morris-lab/CellOracle#20]
Hi there,

Thanks for developing such awesome tool! I have been running the tutorial using my own datasets. However, I've encountered a problem when calculating the network score using links.get_score() function. The data has been log-transformed. 

`Error in if (get_go) { : argument is not interpretable as logical
Execution halted
Error in if (get_go) { : argument is not interpretable as logical`
`Execution halted`
`Modularity is implemented for undirected graphs only.`
`Modularity is implemented for undirected graphs only.`

May I know if there's something wrong with my degree distribution network please? I was using
`links.filter_links(p=0.001, weight="coef_abs", thread_number=2000)`

My KNN calculation and I'm using 10 for the n_comps
`n_comps = min(n_comps, 10)`
![pca1](https://user-images.githubusercontent.com/66819588/84476304-47be0800-acd1-11ea-9363-dd599ed73d82.png)

and I've attached my degree distribution for one of my cluster:
![cluster1](https://user-images.githubusercontent.com/66819588/84475922-b2bb0f00-acd0-11ea-8803-61d597023e8a.png)

Thank you very much for your help.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi yong114,

Thank you for using celloracle!

Could you please tell me about your computational environment?
I want to know these things below.

- Operating system name
- OS version.
- CellOracle version
- Python version,
- Jupyter notebook version

**Comment by yong114** [comment]
Hi Kenji,

Thank you so much for your prompt reply! The pipeline was running smoothly until the network calculation. I installed the CellOracle on the cluster in the Conda environment.
Please find the information as below as requested:

Operating system name - CentOS Linux release 7.6.1810 (Core) 
CellOracle version - 0.3.1
Python version - 3.6.10
Jupyter notebook version - 1.0.0

Sorry I have one more question, I have log-transformed and scaled my data as in tutorial. Would that be the problem or my datasets too noisy please?

Thank you very much for your help again!

**Comment by KenjiKamimoto-wustl122** [comment]
Thank you for letting me know about your environment.

I'm still not 100% sure why you got that error, I tried to update our code to solve the problem.
Could you please re-install celloracle and try the analysis again with the new version of celloracle (0.3.7)?

**Comment by KenjiKamimoto-wustl122** [comment]
Let me answer your second question about log transformation and scaling.

Although we did log-transformation and scaling in the tutorial, these processing is for the calculations of dimensional reduction and clustering, it is not for the celloracle GRN calculation.

We need non-log-transformed data for Network analysis.
And we recover non-transformed data just before GRN calculation in our tutorial notebook.

<img width="935" alt="Screen Shot 2020-06-12 at 18 55 06" src="https://user-images.githubusercontent.com/42547768/84555073-9b841d80-ace0-11ea-8c56-513dc966ffdc.png">

If you are doing the same thing as this tutorial notebook, you have already used non-transformed and non-scaled data for network analysis.

If you skipped this process, please do that.

**Comment by yong114** [comment]
Thank you so much for your kind response! Much appreciated!

I will try to work on that with the latest version, thanks for the explanation.

Will update more soon once I run the analysis.

Thank you again.

**Comment by yong114** [comment]
Hi Kenji,

Many thanks again for your response and after running, it did work with the latest version.
I'm sorry, I have encountered another problem and hope you could help with this please.
I'm currently calculating the gene perturbation of this gene "HIC1" using the function as below and I got the error message:
> oracle.simulate_shift(perturb_condition={goi: 0.0}, n_propagation=3)
`ValueError: Variability score of Gene HIC1 is too low. Cannot perform simulation.`

May I know if that's the problem relates to the predictive models for simulation? I've got the results as below when running the oracle.fit_GRN_for_simulation. But only 2 genes were made for the models.
`genes_in_gem: 24903`
`models made for 2 genes`
`calculating GRN in Platelets`

`genes_in_gem: 24903`
`models made for 2 genes`

I have attached the histogram of gene expression of the gene.
![hist](https://user-images.githubusercontent.com/66819588/84621261-7a5c4080-af1d-11ea-81e3-7d806c945cac.png)

Thank you so much for your help.

**Comment by yong114** [comment]
Hi Kenji,

Many thanks again for your responses. The latest version CellOracle (0.3.7) solved the problem and I have successfully running the analysis. I'm sorry, I have a few questions regarding to the interpretation of the final results please with the Sankey diagram in your tutorial. 
<img width="697" alt="Screen Shot 2020-06-16 at 4 09 28 pm" src="https://user-images.githubusercontent.com/66819588/84737690-cd9cc480-afeb-11ea-87d4-2770d1af854a.png">

Based on the tutorial, I was wondering if GATA1 also involved in the cell transition between Megakaryoctes and GMP (pink flow) / and also between Granulocytes and late GMP (red flow) please (based on the colour flow charts?) Sorry for my questions.

Thank you very much again.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Yong,

I'm glad to hear that CellOracle worked in your environment!

The answer to your question is **Yes**.
Maybe the Gata1 KO simulation suggests that Gata1 KO can induce cell transition from MK to GMP and also Gata1 KO can induce cell state transition from Granulocyts to GMP.

I think these predictions are convincing because it seems that there are several experimental studies to support these predictions.
https://pubmed.ncbi.nlm.nih.gov/11012179/
https://www.frontiersin.org/articles/10.3389/fmed.2017.00115/full

FYI, please let me add some tips below. These tips might help you interpret the results of cell oracle's simulation.

1. **[Tips to interpret sankey diagram]** The snaky diagram is a summary of Markov simulation. In this simulation, we simulate cell transition when we perturb a TF(s). We calculate transition probably using GRN, and we use scRNA-seq data for the initiation state.
The left side of the sankey diagram is a cell state at the initiation, which is intact scRNA-seq data. The right side of the sankey diagram is a predicted final cell state after Malkov simulation. 
If you see a transition from Mk to GMP, it means Mk might become like a GMP if we perturb TF. But, the sankey diagram only shows information about **initial state and terminal state**, it does not always means cells directly convert from cell MK to GMP. There is a possibility that the cells change through a different cell type before reaching the final state. For example, Mk might change into MEP, then this MEP change into GMP. Again, please keep in mind that the sankey diagram only shows information about initial state and terminal state. And the results of this simulation depends on the number of steps in the Markov simulation. Please star the Markov simulation with a small number of steps.

2. **[Difference between cell oracle's simulation and experimental perturbation]** You might want to predict the phenotype of TF KO. But please keep in mind that CellOracle's simulation is not exact same as experimental KO in some viewpoints.
First, CellOracle's simulation uses scRNA-seq data for the initiation state, but your initial state of KO might be different from the scRNA-seq data. In the simulation with the hematopoiesis dataset, we did the Gata1 KO simulation. In the simulation, the Gata1 gene was deleted  **"in the middle of "** hematopoiesis. However, when you perform mouse KO experiment with Gata1 KO mouse, gene KO was **"already done in the beginning"** of hematopoiesis. Thus, the condition of the simulation is not always same as actual experiments. 
We designed celloracle to understand the mechanism how GRN control cell identity intuitively. The  aim of this project is not to predict the exact same phenotype of perturbation experiments. Thus, please use celloracle to analyze the GRN and cell identity in your scRNA-seq data rather than to predict the exact same phenotype of perturbation experiments.

3. **[Potential limitation of celloracle]** The simulation is performed based on GRN connectivity. If you try simulation with a TF that have small number of connection, the accuracy could be bad. Please make sure that your TF of interest have large network degree before doing simulation.  Also, celloracle cannot predict the phenotype of a TF if the TF's regulatory mechanism is strongly affected by the post-transcriptional regulation. It is the limitation of scRNA-seq experiments itself.

4. **[Resource]** We provide information about CellOracle in various format. I hope these resources help your analysis.
YouTube channel: https://www.youtube.com/channel/UCVy_6MUYL594cyNijzD0EVg
Web documentation: https://morris-lab.github.io/CellOracle.documentation/index.html
Preprint: https://www.biorxiv.org/content/10.1101/2020.02.17.947416v3

**Comment by yong114** [comment]
Hi Kenji,

Thank you so much for your kind and detailed explanation! It definitely helpful for me when interpreting the results. Sorry, I have one more question please. As I know, it is crucial to select the significant Tf/ with many connections/high connectivity in the clusters for the GRN simulation, am I right?

Thank you again.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi yong114,

Yes. You're right.
For the simulation, TF need to have decent number of connections in at least one cluster.

If your TF of interest has no connections in a cluster, there are several possible interpretations.

1) The TF does not have significant biological role in the cluster.
2) CellOracle could not detect connections between the TF and its target gene if the genes are dominantly regulated by a post-transcriptional mechanism. CellOracle was designed to analyze only transcriptional GRN.
3) The connection for a TF cannot be detected if base GRN (the output of scATAC-seq analysis) does not contain any data for the TF. 
4)  Technical error.

**Comment by yong114** [comment]
Thank you so much Kenji for your kind explanation! It was really helpful for me!

Thank you again for your time. Cheers.
