### ISSUE TITLE
Single TF of interest ChIP-seq input 

### ISSUE THREAD

**Issue by laijen000** [morris-lab/CellOracle#28]
Hello! Thank you for this awesome tool! In particular, I would love to be able to simulate changes in a scRNAseq data set after a single transcription factor of interest is perturbed. 

From the tutorial, it appears that the GRN is inferred from ATAC-seq data and nearby TF motifs. 
If I have ChIP-seq data for my single TF of interest, is it possible to use this instead of an ATACseq dataset to predict perturbation changes (or is there a way to contribute this added information?) Or is it important for CellOracle to have comprehensive information on all the TFs and their target genes based on motifs in open chromatin regions? 

Thank you! 
Jenny

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Jenny,

The answer depends on the TF.

Celloracle is designed to use comprehensive information on many TFs. We need scATAC-seq data to extract context-dependent enhancer / promoter DNA sequence for whole genes.

(1) If you have Chip-seq data for general promoter enhancer marker molecule such as histone modifier, such Chip-seq data might be a substitute for scATAC-seq data.

(2) But if your gene for Chip-seq is a specific TF rather than broad epigenome marker, such information will not be a substitute for scATAC-seq data. We need information for many gene-gene connections to reconstruct gene regulatory networks.

However, your Chip-seq data for single TF might still be useful: although It **cannot be a substitute** for ATAC-seq data, it will **add** information.

If you want to use Chip-seq data as an additional information, you can import such data to your analysis as follows. 
(Step 1) Make list of target genes of the TF of your interest by analyzing your Chip-seq data. 
(Step 2) Convert this information into a python dictionary. We introduce an example of this step in the tutorial notebook 4 Network analysis 2.3.

**Comment by laijen000** [comment]
That makes sense, thank you so much!
