### ISSUE TITLE
In silico perturbed gene expression values 

### ISSUE THREAD

**Issue by laijen000** [morris-lab/CellOracle#30]
Thank you again for this awesome tool! 

During in silico perturbation simulation, namely "3.2. calculate future gene expression after perturbation", are the predicted expression values for all genes in response to perturbation of a single gene saved somewhere that can be retrieved for downstream analysis such as differential gene expression analysis? 

For example, after simulating GATA1 KO, can we get the predicted differentially expressed genes in a specific cluster of interest? 

Thank you!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Jenny,

Celloracle stores predicted gene expression values for a perturbed condition. But currently, we do not provide a function to export such information because of several reasons.

The main reason is to avoid overinterpretation. Although the celloracle was designed to predict future gene expression, the simulation was designed mainly to be used for cell-identity transition analysis rather than general downstream analysis. The natures of the simulated values are different from that of experimental gene expression values in several viewpoints. Accordingly, we might have a serious problem if we use simulated data in unvalidated methods.
Although it is possible to export predicted values for another downstream analysis, we cannot guarantee the quality of such analysis.
To avoid a potential issue with unexpected usage, we don't provide such functions at least for now.

We are currently validating celloracle in many ways for a better understanding of its power and limitation. New validation results will be reported in a future publication.

Thanks,

**Comment by laijen000** [comment]
I see, that makes sense, thank you! I look forward to learning about future validation results :) 

Is there a way to obtain the new proportions of each cell type in the terminal state after in silico perturbation?

**Comment by KenjiKamimoto-wustl122** [comment]
Current version of celloracle has no function to get that proportion. We will add such function in the future version.

Best,

**Comment by erencshin** [comment]
Hi, @KenjiKamimoto-wustl122 is there a way to get these proportions in version 0.10.14?
