### ISSUE TITLE
error when I try to convert seurat object to anndata object

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [morris-lab/CellOracle#35]
Hi!

I was trying to convert my already analysed data into an anndata object, using the API command, but I get this error:

input file name: /home/jovyan/data/scRNAseq_folder/Seurat_objects/RNAseq_Seurat_UMAP_neighbours_day.31.rds
loading seurat object ...
  seurat object version is 3x
processing data ...
making matrix files ...
[1] "active_assay is RNA"
Error in Matrix::writeMM(obj = SO@assays$RNA@data, file = "tmp/data.mtx") : 
  Cholmod error 'error reading/writing file' at file ../Check/cholmod_write.c, line 634
Calls: <Anonymous> -> <Anonymous>
Execution halted
Build process aborts.

**Comment by KenjiKamimoto-wustl122** [comment]
HI,

It seems that the process crushed when it write single cell RNA-seq read into mtx format.
Although I'm not 100% sure why it crushed, I'm suspecting two things; (i)memory shortage or (ii) permission error.


Please let us check the possibility of memory shortage first.
I'm suspecting memory shortage because this process require relatively large amount of memory.

1) How many genes and how many cells are in your seurat_object?
2) How much RAM memory does your computer have?
