### ISSUE TITLE
GRNs and gene perturbation simulation

### ISSUE THREAD

**Issue by s849** [morris-lab/CellOracle#36]
Hello,

Thank you for developing Cell Oracle. I am interested in using this package to analyze my data (specifically starting from 5. Simulation with GRNs). I am wondering whether I can use GRNs generated by pySCENIC to simulate signal propagation inside a cell with Cell Oracle? Or, do I need to follow your pipeline entirely and generate the GRNs as described here? I want to use Cell Oracle because I am interested in using it to estimate the effect of gene perturbation (either KO or over expression) and its effect on cell fate.

Thank you for your time!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi,

In theory, I think a GRN obtained by SCENIC can be used for a celloracle input.
You can skip several processes of celloracle workflow if you already have a SCENIC's GRN. 
However, you still need to convert SCEINC's GRN into celloracle's GRN because the GRN structure is different. Please see below for the detailed process.

First, You can skip 
- 01_ATAC-seq_data_processing, 
- 02_motif_scan,

Also, you can skip 03_scRNA-seq_data_preprocessing if you have scRNA-seq data in anndata format. 
If not, please start with this step 03.

Next, please do 04_Network_analysis with SCENIC's GRN for an input of celloracle.
But, the input GRN should be given as a pandas-DataFrame like this.

<img width="1068" alt="スクリーンショット 2020-11-22 16 23 56" src="https://user-images.githubusercontent.com/42547768/99918873-7d830600-2cdf-11eb-87f7-1bdf1d812d23.png">


Please convert SCENIC's results into this format. The important requirement of this format is 

1. The first column, "peak_id" stores peak information. In your case, please make a column with random strings. 
2. The second column, "gene_short_name" stores target gene name.
3. The other columns, ( 3~ columns), store Transcription factors binding information. Please enter 1.0 if the TF regulate the gene in the second column. If the TF does not have connection to the gene in the second column, please enter 0.0.

And then, you can input this dataframe into celloracle as follows.

<img width="980" alt="スクリーンショット 2020-11-22 16 23 47" src="https://user-images.githubusercontent.com/42547768/99919067-b5d71400-2ce0-11eb-8e10-c1b4c919b162.png">


For more information, please look at our tutorial notebooks.
In theory, I think the SCECNIC's GRN can be used as an base-GRN of celloracle analysis. 
However, I strongly recommend trying celloracle's tutorial first to know the basic workflow.
