### ISSUE TITLE
NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [morris-lab/CellOracle#38]
Hi,

I was trying to rerun celloracle (it worked previously). I encountered this error:
 NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method. 

when running "tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome= "hg38")"

**Comment by KenjiKamimoto-wustl122** [comment]
Hi,

It seems that this error was due to the installation error of BEDTools, which is a dependent software of pybedtools.
I thought BEDTools is automatically installed when you install pybedtools with conda, sometimes you might get such error. 
In that case, please install the latest version of BEDTools manually.

I will add a notes about this issue s to our Celloracle web documentation.
Thank you for reporting error!

Kenji
