### ISSUE TITLE
threshold for tfi.filter_motifs_by_score

### ISSUE THREAD

**Issue by sa95078** [morris-lab/CellOracle#39]
Hi, 

Thank you for sharing the wonderful package. I am working through the tutorials. It is unclear to me how the CellOracle score for a certain motif/locus defined is defined and how a threshold, which was set at 10.5 in the tutorial 02, is determined.

Thank you,

James

**Comment by KenjiKamimoto-wustl122** [comment]
Hi James,
Usually, we recommend thresholding at 10 because we found this threshold gives us good results. 
If we use a lower threshold, we can detect many binding sites, but we also get more false-positive sites.
If we use a higher threshold, we can eliminate noise, resulting in fewer false-positive sites, but a higher threshold value also reduces the number of correct sites.
We need to find the right balance considering these things.

In your analysis, please start with a threshold at 10 or 10.5. If it does not work, please find a better threshold value for your analysis.

**Comment by sa95078** [comment]
Thank you for the reply! Are there quantitative measurements for a "good" GRN network. For example, when I compared networks created using tissue-specific or the default TF dictionaries, I found only small differences in the degree of distribution. As expected, the centrality ranking for TFs was different. But without enough ground true evidence, how should we measure a GRN?

I also have a new question. When using scRNA-seq to prune the base network, does CellOracle examine only a positive correlation between TF and its targets? If it calculates both positive and negative correlation, can we get the network output so we can examine the transcription activity of a specific TF?

**Comment by KenjiKamimoto-wustl122** [comment]
Hi James,

Thank you for asking a question!
I agree with you and what you pointed out here is very important.

We are now getting revision to publish CellOracle in a peer-reviewed paper. 
And we are doing benchmarking CellOracle with experimental ground truth.
We think we can answer your first question with detailed explanations and data in publication soon! 

We are using both positive and negative correlation between TF and targets. In this process, you can get a list or  matrix of network weight. If a network weight value, "coef_mean" is negative, it means there might be a negative relationship between the TF and  the target gene. 
<img width="743" alt="スクリーンショット 2021-01-28 13 12 41" src="https://user-images.githubusercontent.com/42547768/106187244-f896eb80-616a-11eb-94e7-894d6a1db683.png">

Also, please keep in mind that celloracle makes GRN for each cell cluster. You will get cell-type specific TF-target connection activity score.
