### ISSUE TITLE
ATACseq as 'base' GRN structure.

### ISSUE THREAD

**Issue by Willtwl** [morris-lab/CellOracle#40]
Hi, thank you all for developing this computational tool.
I am new to bioinformatics, would like to use CellOracle to practice finding and inferring GRNs.

If I were to use a human ATACseq data to assemble the 'base' GRN structure, do I have to process the raw data first such as quantifying the transcripts reads from the raw data or alignment them via bowtie2? Or do I just import them as fastq.gz files using the code in the tutorial step 1 (ATAC-seq data preprocessing)?
Because I notice the mouse ATACseq file obtained from 10x genomics are already in a different format.
Thanks in advance!

Regards,
Wil

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Wil,

I' m sorry but Celloracle does NOT contain any alignment function because it is a downstream analysis tool.
If you have fastq files, please do alignment with another tool.

We have mainly two options for the preprocessing of scATAC-seq data.

1. Using Cicero
2. Another way 

We recommend using Cicero. If you are not familiar with the scATAC-seq analysis with Cicero, please find the information [here](https://cole-trapnell-lab.github.io/cicero-release/docs/). Also, you can find information how to make inputs data for Cicero [here](https://cole-trapnell-lab.github.io/monocle3/docs/starting/#cell_data_set). I think you can also find a way to make cicero data with your data.

Although we usually recommend using Cicero to make input data of base GRN, using Cicero is not mandatory but just one of the options. 
If you want, you can create a base GRN without Cicero.
To construct base GRN, Celloracle needs two data as follows.

1. "scATAC peak list" 
<img width="682" alt="スクリーンショット 2021-01-19 午後2 44 36" src="https://user-images.githubusercontent.com/42547768/105091087-f0e98f80-5a64-11eb-9dde-2de26c5eb10f.png">

2. Coaccess information between peaks
<img width="671" alt="スクリーンショット 2021-01-19 午後2 44 43" src="https://user-images.githubusercontent.com/42547768/105091094-f34be980-5a64-11eb-98fa-fefdf491b09a.png">

Please prepare these data in a way you like, and then start CellOracle analysis from [this step](https://morris-lab.github.io/CellOracle.documentation/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/02_preprocess_peak_data.html#1.-Load-data-made-with-cicero)

**Comment by Willtwl** [comment]
Thank you for your response Kenji!
So just to clarify, I can simply use Cicero on my raw ATACseq data and it will return peaks and co-access score?
But I do not understand how to layout these ATACseq data in the form of celldataset prior to running Cicero. Hope you guide me through this. Thanks Kenji!
I apologise again as I am really new to these. 

Regards,
Wil

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Wil,
Yes, please use Cicero and get co-access score.
How to input the your ATAC-seq data to Cicoro depends on your data format.
You can find detailed instruction in the Cicero's web documentation. 
And we also providing an example of Cicero analysis [here]( https://morris-lab.github.io/CellOracle.documentation/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/01_atacdata_analysis_with_cicero_and_monocle3.html)

Kenji
