### ISSUE TITLE
Inconsistent plots with adata.raw.X and imputed_counts + kernel dies at get transition probability

### ISSUE THREAD

**Issue by vittoriabocchi** [morris-lab/CellOracle#41]
Hi, thank you all for developing this really useful computational tool!
I am having some problems with the predictive GRNs/TF that come out of the analysis. They don’t seem to replicate what I analyzed previously with scanpy (and canonical marker genes of each cell states) and when I plot the expression levels of “imputed_count” and adata.raw.X  I get very different results (see attached figure). 

![plot](https://user-images.githubusercontent.com/36735148/105063161-b4755e00-5a7b-11eb-9458-4df0491f7612.JPG)

I don’t have ATAC-seq data so I used Scenic data that I previously calculated to make a custom dictionary following the steps described here “Make TF info dictionary manually”.

Furthermore, when I get to this stage 
Get transition probability:
oracle.estimate_transition_prob(n_neighbors=200, knn_random=True, sampled_fraction=0.5)
the kernel dies.
Any suggestion would be greatly appreciated!
Thank you!
vittoria

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Vittoria, 

I would like to see your data to identify why your imputed count looks different from the original one.
If possible, can you send me your oracle object data and your jupyter notebook?
If you don't mind, please send your data to my e-mail address: kamimoto[at]wustl.edu (please substitute [at] with @).
Please locate your data on google drive or something similar and send me the link to my e-mail address because the data should be massive.
Of course I'll keep your data confidential.


For your second question, I'm guessing it is because of a memory error. 
The transition probability calculation requires a lot of memory.
Regarding this, please let me ask some questions as follows.

- How many cells are there in your data?
- How many genes are there in your data?
- Please tell me your computational environment: CPU, memory size, OS, etc.
