### ISSUE TITLE
Error in knn_imputation

### ISSUE THREAD

**Issue by gldong** [morris-lab/CellOracle#42]
Hello,

I encountered an error from velocyto when running 

`oracle.knn_imputation(n_pca_dims=n_comps, k=k, balanced=True, b_sight=k*8, b_maxl=k*4, n_jobs=4)`

I also tried using the dataset Paul et al. 15 as in the tutorial and followed the exact same steps (with adjusted annotations). I was able reproduce all the output but still ran into the same error. Please see the error message below. 

![image](https://user-images.githubusercontent.com/22530164/105619568-d0516a80-5dc1-11eb-843f-74f9bae67ac7.png)

Thanks in advance!
Lan

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Lan,

The error was caused by numba, one of the packages used inside celloracle.
We got a similar error report from another user. I'm sorry for the inconvenience.
I'm planning to fix this error and release the next version of celloracle as soon as possible.
I think we can do it in a week! I'll let you know when it is fixed.
Thank you for letting us the issue!

Kenji

**Comment by gldong** [comment]
I see - thanks a lot Kenji! I'll keep an eye out for the update :)

Lan

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Lan,

I updated CellOracle to fix the bug. 
Can you re-install celloracle and try your analysis again?
Hopefully, the new version, celloracle0.6.3, will work without the error.

Kenji

**Comment by gldong** [comment]
Hi Kenji,

Thanks for the fast update! I re-installed version 0.6.3, but got an error with gimmemotifs when importing.

![image](https://user-images.githubusercontent.com/22530164/105906821-2efd2b00-5ff2-11eb-92b4-b10b332fd10d.png)
![image](https://user-images.githubusercontent.com/22530164/105906966-6075f680-5ff2-11eb-9194-091244e0bda6.png)

I saw a similar error on gimmemotifs' github page (https://github.com/vanheeringen-lab/gimmemotifs/issues/57) and tried re-installing gimmemotifs with 

`pip install git+https://github.com/simonvh/gimmemotifs@0.14.4`

but got the same error. Did I miss something?

Thanks,
Lan

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Lan,
I'm sorry but I'm not sure why you get this error. 
As you pointed, this error due to the gimmemotif.

We'll try to look into it, but we cannot modify gimmemotif package even if we found the cause of the error.
Could you please contact the gimmemotif team to ask question about it?

Sorry for the inconvenience again.

**Comment by gldong** [comment]
Thank you Kenji for getting back to me - I searched around on gimmemotifs' github page and was actually able to solve it!

I followed the steps here: https://github.com/vanheeringen-lab/gimmemotifs/issues/157#issuecomment-742333178

Both importing and knn_imputation work now. Thanks again for addressing this and putting out a new version so fast!
