### ISSUE TITLE
Issue with Simulation

### ISSUE THREAD

**Issue by annrosebright** [morris-lab/CellOracle#49]
Hi, 
Thanks for creating a great tool. I am trying to do the simulation test for some of the TFs I am interested in. For Two of the factors (Errb4 and Meis2), I am getting the following error. For one it complaints of not finding the gene in the var slot and for the other, there seems to not have enough regulatory connection in the GRNs. I was wondering if there are ways to tweak the network construction commands so that we could see the results for any gene of interest. 
-Are there ways in which the gene of interest does not need to be variable? 
-Also is possible to play around with the cut-off score to increase the connections in the network.

I am attaching both the errors as screenshots. 
![Erbb4](https://user-images.githubusercontent.com/13627744/115024840-ee120580-9ec0-11eb-8057-de32a6a58533.png)

![Meis2](https://user-images.githubusercontent.com/13627744/115025220-6082e580-9ec1-11eb-9068-9938167105b4.png)

Thanks in advance

Best,
Ann

**Comment by KenjiKamimoto-wustl122** [comment]
Thank you using celloracle!

There are some possible scenarios where celloracle cannot perform simulation.

1. The gene is not in the gene expression marix after gene filtering.
2. The gene does not have DNA-binding motifs. 
3. TF have no connection in the inferred GRN
4. Gene expression level is too low or gene expression contains too many dropout. In this case, it is possible to do calculation. But the results can be inaccurate.

In your case, it seems that Meis2 is not included in the scRNA-seq data. This is the case1 in the list above. I guess the gene was filtered out in the preprocessing step. Pease go back to the preprocessing step, and change thresholding parameter so that Meis2 gene is included in your data.

For Erbb4, I'm suspecting that Erbb4 is not included in the base GRN because of the lack of DNA binding motif information. CellOracle constructs base GRN using DNA binding motifs and DNA sequence in ATAC-seq data. If there is no DNA binding motif data, CellOracle cannot perform simulation.
You can check whether a gene is included in the base GRN or not as follows.

`oracle._process_TFdict_metadata()`
`oracle.adata.var`

<img width="494" alt="スクリーンショット 2021-05-26 午後5 21 41" src="https://user-images.githubusercontent.com/42547768/119738811-eaba5400-be46-11eb-9995-db015bb2b6b8.png">

Please look at "isin_TFdict_regulators".
If the value is False, it means the gene does not have motif data.

In that case, you still put the gene into base GRN by entering potential target gene list manually. Please read [this section](https://morris-lab.github.io/CellOracle.documentation/notebooks/04_Network_analysis/Network_analysis_with_Paul_etal_2015_data.html#2.3.-(Optional)-Add-TF-info-manually) for detail.
