### ISSUE TITLE
Variability score of a gene is too low. Cannot perform simulation.

### ISSUE THREAD

**Issue by yong114** [morris-lab/CellOracle#50]
Hi Kenji (@KenjiKamimoto-wustl122),

Thanks for developing such amazing tool!
I have a couple of questions please. I was testing two different conditions. For example: tumour and normal, I found a gene which had high network score and I was able to perform the knockout simulation using that gene in the tumour samples. The results were interesting. However, when I tried to use that particular gene to perform the gene knockout simulation in healthy samples it shows an error saying that "Variability score of a gene is too low. Cannot perform simulation." 

I was just wondering if you have any explanation for that please? Does it mean that this particular TF gene has very low variability score in normal samples (/healthy) and does not involve in any transition in the cell types please? Both conditions (all samples) using 3000 high variable genes and 20k cells.

Second question is that would it be possible to extract the results from the simulation for some tests (probability of a cell state transition based on the simulated data) ? like in a data frame please? 

Thank you very much!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi yong114,

Thank you  for using celloracle. And sorry for the delayed response!

CellOracle calculate top 1000 variable genes when you import gene expression data, and you can get the error "Variability score of a gene is too low. Cannot perform simulation" if you try to simulate a gene which are not in the top 1000 genes.


Here are two solutions.
(1) Please try to update CellOracle. CellOracle codes has been updated recently. You can do calculations even the gene is not in the top 1000 variable gene list. You will get a similar warning message, but it is fine.

(2) When you do simulation please set `ignore_warning=True`.

For example, please run the codes like this.
`oracle.simulate_shift(perturb_condition={goi: 0}, n_propagation=3, ignore_warning=False)`

You can avoid getting the error.

**Comment by KenjiKamimoto-wustl122** [comment]
For the second question, I will make an example notebook to explain how to extract transition probability data in a few days.

**Comment by KenjiKamimoto-wustl122** [comment]
I made notebook to explain how to extract transition probability data.
Please take a look this notebook. 
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/05_simulation/Analyze_transition_probability_with_Paul_etal_2015_data.ipynb

I hope it helps.

**Comment by yong114** [comment]
Hi Kenji,

No worries at all and thank you so much for your kind response. I have managed to perform the simulation with the latest version. I have another quick question please. In your notebook, I was just wondering if the "red triangle" = cell of interest please? And also does it mean that the darker colour of the dot = higher transition probability score of the neighbouring cells please? Thank you again.

**Comment by KenjiKamimoto-wustl122** [comment]
@yong114 

Yes, exactly. The red triangle is the cell of interest, and the darker color means higher transition probability.

**Comment by yong114** [comment]
![image](https://user-images.githubusercontent.com/66819588/120137281-473abc00-c217-11eb-9318-6af036521244.png)


Hi Kenji,

Thank you very much for your reply. Sorry for interrupting again, I was just wondering what does the colour and the lines mean in the attached image for Markov simulation please?

Thank you so much again, much appreciated.

**Comment by yong114** [comment]
Hi Kenji,

Very sorry to interrupt again, I have another quick question if you don't mind. 
I'm interested in looking at the gene overexpression (other than gene KO), for example I was wondering how to set the value of the candidate genes to twice their maximal imputed gene expression value please? Is it something like this?
`sc.get.obs_df(oracle.data, keys=[goi], layer="imputed_count").max()`

Then how to proceed further with this function please, should I change to 100?
`oracle.simulate_shift(perturb_condition={goi:100.0}, n_propagation=3)`

Thank you very much.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi yong114,

First, let me answer your question about the Markov simulation.

The plot is the results of the Markov chain simulation. As you know, we got the transition probability between cells.
We did a Markov chain simulation using this probability. Please see [this](https://en.wikipedia.org/wiki/Markov_chain) if you are not familiar with the Markov chain.

The red dot in the plot is a single cell that is randomly picked up. We also see some lines. Each line represents the results of the Markov chain simulation. The Markov chain started with the red cells, and the line is the history of the cell state transition. We did several simulations, so we have multiple lines. We got different lines even if we started from the same cell because the process of Markov simulation is not deterministic. 

By the way, recently, I made the Markov chain simulation analysis deprecated just because the interpretation may be difficult.
Although you can still do this Markov chan analysis, this analysis is not included in our tutorials. The script for the Markov chain simulation was moved to [this place.](https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/05_simulation/archived_210531_Gata1_KO_simulation_with_Paul_etal_2015_data.ipynb)

Also, we devised a new function for celloracle downstream analysis to substitute Markov chain analysis. It is coming soon.

**Comment by KenjiKamimoto-wustl122** [comment]
@yong114 

Let me answer the second question about the over-expression.

As you said, we can get the maximal gene expression value like this.
<img width="735" alt="スクリーンショット 2021-06-02 午後2 54 39" src="https://user-images.githubusercontent.com/42547768/120543953-818c9080-c3b2-11eb-8e70-3746c2b1c761.png">

Please enter **the value itself** into the oracle.simulate_shift function. The perturb condition format is not the percentage.


<img width="745" alt="スクリーンショット 2021-06-02 午後2 50 18" src="https://user-images.githubusercontent.com/42547768/120544136-b4368900-c3b2-11eb-8868-7be7625712a9.png">

If you want to set the value of the candidate genes to twice their maximal, you can do it as follows.
`max_value = sc.get.obs_df(oracle.adata, keys=[goi],  layer="imputed_count").max().values[0]`
`oracle.simulate_shift(perturb_condition={goi: 2*max_value},  n_propagation=3)`

**Comment by yong114** [comment]
Thank you so much Kenji! Look forward to the new version of CellOracle!
