### ISSUE TITLE
Reference genome for new species

### ISSUE THREAD

**Issue by ifanirene** [morris-lab/CellOracle#52]
Hi Kenji,

Thank you and the team for this fantastic package! We performed _in silico_ gene over-expression in mouse heart scRNA-seq and the result matched well to the real data generated in the lab! For broader usage of this great tool, I'm wondering if you could add Guinea pig reference genome for TSS annotation in the future, or let us know if there is a way to incorporate custom genomes.

Best,
Irene

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Irene,

Thank you for using celloracle!

It's possible to add Guinea pig reference genome data.
Although I cannot do it right now due to the lack of time,  I will try it when I have time. Can you please wait for a while?  I will notify you when I add the Guinea pig data.

Best,
Kenji

**Comment by ifanirene** [comment]
Hi @KenjiKamimoto-wustl122,

Yes of course we can wait. We will be exploring the mouse scMultiome data for now.
Here is the genome build download page if you need it: https://uswest.ensembl.org/Cavia_porcellus/Info/Index?db=core 

Good luck with submission!
Irene

**Comment by KenjiKamimoto-wustl122** [comment]
Hi @ifanirene 

Sorry for the delayed response, but finally, I made some updates as follows.

1. I added reference TSS data for the Guinea Pig reference genome, "Cavpor3.0", to CellOracle. The TSS data for Cavpor3.0 was generated from the Ensembl database. 
The new data is available with CellOracle ver 0.8.4. Please update CellOracle to try this new data.
And please let me know if you find a problem with it.

2. Also, I shared my scripts for the Guinea Pig TSS data preparation. Hopefully, the script can be used for another TSS data preparation if you have gff3 data in Ensembl format.
Usually, we generate TSS data from the Homer database, but the Guinea Pig data was not available in Homer. Thus we made new functions to generate TSS data from the Ensembl database.
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/misc/Make%20tss%20reference%20datafile%20from%20Ensembl%20database/1_make_tss_referenece_from_ensemble_gff3_file.ipynb

3. FYI, Here are my script to generate the TSS file from the Homer database.
https://github.com/morris-lab/CellOracle/tree/master/docs/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/misc/Make%20tss%20reference%20datafile%20from%20homer%20database

4. If you have another request for a new species in the future, I will add the new TSS data. Please let me know. If the genome annotation is available in Ensembl, I can quickly generate TSS data because I can use the same script next time.

**Comment by ifanirene** [comment]
Hi @KenjiKamimoto-wustl122,
Can't wait to try these fantastic add-ons!  I have never used python before but was able to generate reproducible result with your notebooks and instructions. Thank you again for making a new way to explore multiomic data
