### ISSUE TITLE
seurat-monocle object conversion to anndata 

### ISSUE THREAD

**Issue by annrosebright** [morris-lab/CellOracle#53]
Hi 

I am trying to implement cell oracle on Seurat-monocle analyzed data.  I am able to successfully convert the rds file to anndata.  In the object, there are dimensionality reduction from  Seurat and monocle (Fig 1). But after converting to anndata I can only find X_umap (Fig 2 and 3).  Is there a way to export all reductions?  I would like to use the dimensions from monocle for plotting and further analysis.
  
![Fig1](https://user-images.githubusercontent.com/13627744/123288542-f49ba980-d50f-11eb-9786-a080201c884b.png)
![Fig2](https://user-images.githubusercontent.com/13627744/123288552-f82f3080-d50f-11eb-83b1-0bab8646610d.png)
![Fig3](https://user-images.githubusercontent.com/13627744/123288563-fb2a2100-d50f-11eb-866e-7281c9f689c0.png)

**Comment by KenjiKamimoto-wustl122** [comment]
Hi annrosebright,

Thank you for asking question!

We've noticed this issue recently, and we updated celloracle data conversion module.
Can you please re-install celloracle and try to convert your data again with new version of celloracle?
I think you can get all reductions if celloracle version is higher than 0.6.12. 

You can check celloracle version as follows.

<img width="328" alt="スクリーンショット 2021-06-24 午前11 38 15" src="https://user-images.githubusercontent.com/42547768/123300996-c2268800-d4e0-11eb-9bbd-f9b133469ccb.png">

I hope it works.
Kenji

**Comment by annrosebright** [comment]
Hi Kenji,

Thanks a lot for the quick response. Indeed with the update, I was able to get all the reductions in the converted object. But still, when I try to plot it using the monocle umap reduction, it still plots the Seurat one (pic attached).  Could you please help me solve this? 
And another issue is that, even though I set the coloring to clusters, it still gives a gradient (black to red). I tried setting the default identity of the Seurat object to clusters before the conversion, but it did not help.   
![Screenshot 2021-07-02 at 11 57 48](https://user-images.githubusercontent.com/13627744/124266725-9d14c380-db37-11eb-8352-eeccf4c05f6a.png)

**Comment by KenjiKamimoto-wustl122** [comment]
@annrosebright 

Thank you for asking a question.

Answer to the 1st question)
 Scanpy's umap plotting function `sc.pl.umap` uses embedding data named "X_umap".
`sc.pl.umap` does not work for another embedding name.
When you want to use another data for visualization, we need to use `sc.pl.embedding`.
In your case, you can visualize your monocle umap embedding as follows.
`sc.pl.embedding(adata, basis="X_umap_mono", color=clustering)`

For more information, please look at Scanpy's documentation. https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.embedding.html#scanpy.pl.embedding


Answer to the 2nd question)
You got continuous black to red coloring because your clustering data was recognized as continuous number data instead of category data. 
The data conversion function keeps data type when the data is converted from Seurat/monocle object into anndata. If your clustering information is stored as a numerical type in the Seurat/monocle metadata object, the data type will be stored as a numerical data type after the data conversion.
Scanpy selects the visualization method judging from the data type information, not the data value itself.  For example, suppose you have metadata like this:  [0, 1, 6, 2, 5,...]. In that case, the data will be visualized as continuous data if the data type is numerical. In contrast, it will be visualized as a category when the data type is the object.  

So we need to modify the data type manually. I propose two options.

Option1) After data conversion,  you can change the data type in your metadata.
In your case, you can change the clustering data type as follows. Then, please try to visualize it. 
`adata.obs[clustering] = adata.obs[clustering].astype("object")`

Option2) Before doing data conversion, please change the data type of your clustering metadata.
`seurat_object@meta.data[, "DATA COLUMN NAME"] <- factor(seurat_object@meta.data[, "DATA COLUMN NAME"])`
And then, please convert the Seurat object.

I hope it works.

Kenji
