### ISSUE TITLE
installation dependencies

### ISSUE THREAD

**Issue by daniel-spies** [morris-lab/CellOracle#57]
First of all thanks for the great tool! 

I now tried to install CellOracle on a new machine, unfortunately some dependencies in the current github setup requirements are not properly resolved.

CellOracle depends on numba 0.50.1 which is incompatible with pynndescent >= 0.47 and conserquently umap-learn>=0.4.6, also it requires llvmlite<=0.33.0 which is incompatible with python 3.9+.  

I'm not sure if only I had this installation troubles as I first thought the numba version is not properly specified and thus subsequently messes up the other packages, but I guess it's simply because the requirements file is not named properly ("i"missing).

But the initial reason was the wrong python 3.9 version, so maybe just mention this in the documentation.

best
Daniel

**Comment by KenjiKamimoto-wustl122** [comment]
@daniel-spies 


Thank you for the feedback.
I will update the file name of "requrements.txt".
But fortunately, its is not related to this issue because the file name was copy and pasted in the setup.py file, and the "requrement.txt" file is properly recognized by setup.py.
<img width="444" alt="スクリーンショット 2021-07-28 午前9 14 20" src="https://user-images.githubusercontent.com/42547768/127337832-aa3670a0-0856-402a-a918-3f24348041f9.png">

I'm sorry for the silly typo anyway! And thank you again for the feedback!

As you pointed, I guess the cause of the problem is python3.9 and numba.
I'm restricting the numba version because I recently found numba <0.50.1 caused a severe error in a CellOracle dependent package. We need to use the recent version of numba. 


An easy solution is using python 3.6.
Could you please use python3.6 or use our docker image?

Also, I will look into the dependent package compatibility in the python 3.9 environments 
and put these information on our web documentation.

Kenji

**Comment by daniel-spies** [comment]
Hi Kenji, In this case setting the minimum requirement to numba>=0.50.1 would already help and allow later python versions as well as more recent dependencies of other packages.  I’m using a python 3.8 now so it’s working, though in a first run also the Seurat singleCellExperiment to AnnData conversion made some hickups when using custom names for the embeddings as scanpy doesn’t have the option to select the embedding by name (I’m new to scanpy so I might have overlooked some options) .  Thanks for the fast reply, I’ll keep you updated. BestDaniel Sent from Mail for Windows 10 From: Kenji KamimotoSent: Wednesday, July 28, 2021 5:35 PMTo: morris-lab/CellOracleCc: daniel-spies; MentionSubject: Re: [morris-lab/CellOracle] installation dependencies ***@***.*** you for the feedback.I will update the file name of "requrements.txt".But fortunately, its is not related to this issue because the file name was copy and pasted in the setup.py file, and the "requrement.txt" file is properly recognized by setup.py.I'm sorry for the silly typo anyway! And thank you again for the feedback!As you pointed, I guess the cause of the problem is python3.9 and numba.I'm restricting the numba version because I recently found numba <0.50.1 caused a severe error in a CellOracle dependent package. We need to use the recent version of numba.An easy solution is using python 3.6.Could you please use python3.6 or use our docker image?Also, I will look into the dependent package compatibility in the python 3.9 environmentsand put these information on our web documentation.Kenji—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KenjiKamimoto-wustl122** [comment]
@daniel-spies 

Although I understand setting dependent package using ">=" might be useful, I still would like to specify version using "=".
It is because the numba package is actively developed, and we are not sure the newer version works. 
What I confirmed is number=0.50.1 works, and I could not check all versions frequently because of the lack of my time.
We would appreciate it if you understand the situation; using "=" instead of ">=" is an easy and safe way for us to keep the package stable.

For scanpy, you can use `sc.pl.embedding()` function to visualize any custom embedding.
Please see this for more information. https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.embedding.html#scanpy.pl.embedding

This previous issue #53 may be useful for you. Please take a look at this.

Kenji

**Comment by daniel-spies** [comment]
Sure, totally understand, thanks for the pointers.  issue can be closed then

many thanks
daniel
