### ISSUE TITLE
Remove velocyto dependency? (enhancement)

### ISSUE THREAD

**Issue by ekernf01** [morris-lab/CellOracle#85]
Hi Kenji, we just finished using CellOracle as part of a class project here at JHU. Since it is ordinarily hard to test installation of a package on so many different operating systems, we thought it might be useful to share one obstacle that a lot of students encountered. The biggest obstacle was definitely on Macs, getting compilers with openMP support, which are needed to compile velocyto's C code. It was especially hard on M1 macs. If it is possible to remove the velocyto dependency, or even just the parts of velocyto written in C, it would probably open up CellOracle to a broader set of users.

**Comment by KenjiKamimoto-wustl122** [comment]
@ekernf01 

Thank you for the feedback!
As you reported, velocyto's C code may cause difficulty in the macOS.
We will try re-implementation / refactoring to remove such issues caused by the celloracle's dependent package. 

Also, we are adding test codes and working on various code refactoring to improve stability and usability.
I'm estimating we can release a major update in June or July.

Thank you for the great feedback, again!

**Comment by agreco92** [comment]
Hi @KenjiKamimoto-wustl122  and @ekernf01, 

I can't manage to install velocyto on my M1 mac, do you have a fix that worked for this?

Thank you!
Alessandro
