### ISSUE TITLE
Optimal Perturbations to transition from Cell Type A to Cell Type B

### ISSUE THREAD

**Issue by rattey** [morris-lab/CellOracle#87]
Hello,

The tutorial is super helpful for knocking out genes of interest, and the Markov chain functions are well-documented enough on the API to easily predict the cell transitions for a given perturbation - thank you for that! I am interested in a related but slightly different analysis - is there a way to use the Markov chains to predict which perturbations would be most likely to transition a given Cell Type A to a given Cell Type B?

If there is not built-in functionality for such an analysis, are the results of the Markov simulations directly comparable to the point that we could loop through individual knockouts of a large list of transcription factors and compare how many cells from Cell Type A transition to Cell Type B for each knockout as a way of selecting key genes for further analysis?

**Comment by KenjiKamimoto-wustl122** [comment]
@rattey 

Thank you for using cellroacle!
I'm so sorry that we have stopped developing the Markov simulation functions.
Instead of developing the Markov simulation functions, we are now providing perturbation score metrics as an alternate downstream analysis after perturbation vector calculation.
https://morris-lab.github.io/CellOracle.documentation/notebooks/05_simulation/Gata1_KO_simulation_with_Paul_etal_2015_data.html#5.-[This-step-is-optional]-Compare-simulation-vector-with-development-vectors
