### ISSUE TITLE
get_network_scores function issue

### ISSUE THREAD

**Issue by andrewjkwok** [morris-lab/CellOracle#90]
Hi,

Thanks for this very cool and extensive package and documentation. I've been trying to v0.10.8 to run now that it's all in python without R dependencies, but am running into a little trouble with the `links.get_network_scores()` function.

Specifically, I get a strange error that says:
`TypeError: Source and target IDs must be 0-based integers, found types [dtype('O'), dtype('O')]`

However, when I look at the filtered links dataframe, all looks normal to me:

```
source | target | coef_mean | coef_abs | p | -logp
-- | -- | -- | -- | -- | --
MEF2A | MIR181A1HG | 0.398907 | 0.398907 | 8.415643e-18 | 17.074913
EZH2 | TAFA2 | -0.359081 | 0.359081 | 4.415633e-14 | 13.355007
THRB | XIST | 0.348288 | 0.348288 | 1.583173e-14 | 13.800472
MYB | TAFA2 | 0.266768 | 0.266768 | 1.272329e-14 | 13.895401
FOSB | MIR181A1HG | -0.240396 | 0.240396 | 6.984626e-14 | 13.155857
... | ... | ... | ... | ... | ...
BACH1 | ZEB2 | 0.039779 | 0.039779 | 1.358256e-10 | 9.867018
KLF6 | ZMYND8 | -0.039777 | 0.039777 | 1.416056e-11 | 10.848919
KLF6 | DISC1FP1 | -0.039773 | 0.039773 | 5.599931e-11 | 10.251817
ZEB1 | STK17B | 0.039768 | 0.039768 | 8.592919e-09 | 8.065859
EGR1 | GPC6 | 0.039757 | 0.039757 | 5.218079e-
```

As such, I'm a little confused as to what the error is even referring to? Please let me know if further information would be helpful. As this should be an issue with the relatively small `links` object, I'd be happy to share it if it helps troubleshooting/debugging.

**Comment by KenjiKamimoto-wustl122** [comment]
@andrewjkwok 

Thank you for the feedback!
We could reproduce the same error.  
The error was due to the recent change in the python-igraph codes, and your links data has no problem.
We updated the celloracle get_network_scores function today to deal with this issue.
I hope the new version, celloracle 0.10.10, works now.
Can you please try to update celloracle and do the network analysis again with celloracle 0.10.10?

Thank you again for reporting the issue!

**Comment by andrewjkwok** [comment]
Thanks for the super quick response. I can confirm that it's working now after the update!
